site_name: scrapy-webarchive
site_description: 
site_url: https://github.com/q-m/scrapy-webarchive

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage:
      - Usage: usage.md
      - Advanced Usage: advanced_usage.md
  - Settings: settings.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences