site_name: scrapy-webarchive
site_description: 
site_url: https://github.com/q-m/scrapy-webarchive

theme:
  name: material

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Usage:
      - Usage: usage.md
      - Advanced Usage: advanced_usage.md
  - Settings: settings.md