name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: pip install -r requirements-tests.txt
      - name: Ruff
        run: ruff check scrapy_webarchive tests
      - name: Mypy
        run: mypy scrapy_webarchive

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: pip install -r requirements-tests.txt
      - name: Test
        run: coverage run -m pytest tests
      - run: coverage report
      - run: coverage html --title "Coverage for ${{ github.sha }}"
      - name: Store coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true
