name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install -r requirements-tests.txt

      - name: Ruff
        run: ruff check scrapy_webarchive tests

      - name: Mypy
        run: mypy scrapy_webarchive

  test:
    name: unittests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv:
          - py37-scrapy29
          - py312-scrapy29
          - py38-scrapy210
          - py312-scrapy210
          - py38-scrapy211
          - py312-scrapy211
          - py312-scrapymaster
        include:
          - toxenv: py37-scrapy29
            python-version: 3.7 
          - toxenv: py312-scrapy29
            python-version: '3.12'

          - toxenv: py38-scrapy210
            python-version: 3.8 
          - toxenv: py312-scrapy210
            python-version: '3.12'

          - toxenv: py38-scrapy211
            python-version: 3.8 
          - toxenv: py312-scrapy211
            python-version: '3.12'

          - toxenv: py312-scrapymaster
            python-version: '3.12'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: |
            tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        continue-on-error: ${{ contains(matrix.toxenv, '-scrapymaster') }}
